
[ClassVersion("0.1.0.0"), FriendlyName("AFIdentity")]
class xAFIdentity : OMI_BaseResource
{
    [Key] String Name;
    [Required] String AFServer;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] Boolean IsEnabled;
	[Write] String Description;
};

