
[ClassVersion("0.1.0.0"), FriendlyName("PIPoint")]
class xPIPoint : OMI_BaseResource
{
    [Write] String PtSecurity;
    [Key] String Name;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] String DataSecurity;
    [Required, Description("PI Data Archive name for connection")] String PIDataArchive;
};

