
[ClassVersion("0.1.0.0"), FriendlyName("PIIdentity")]
class xPIIdentity : OMI_BaseResource
{
    [Write] Boolean CanDelete;
    [Write] Boolean IsEnabled;
    [Required, Description("PI Data Archive name for connection")] String PIDataArchive;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] Boolean AllowUseInTrusts;
    [Key, Description("unique name")] String Name;
    [Read] Boolean AllowExplicitLogin;
    [Write] Boolean AllowUseInMappings;
	[Write] String Description;
};

