
[ClassVersion("0.1.0.0"), FriendlyName("PIMapping")]
class xPIMapping : OMI_BaseResource
{
    [Write] String PrincipalName;
    [Write] String Description;
    [Required, Description("PI Data Archive name for connection")] String PIDataArchive;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] Boolean Enabled;
    [Key] String Name;
    [Write] String Identity;
};

