
[ClassVersion("0.1.0.0"), FriendlyName("AFMapping")]
class xAFMapping : OMI_BaseResource
{
    [Write, Description("Description")] String Description;
    [Write, Description("AF Identity Name")] String AFIdentityName;
    [Required, Description("AF Server name for connection")] String AFServer;
    [Key, Description("unique name")] String Name;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Windows account")] String Account;
};

