
[ClassVersion("0.1.0.0"), FriendlyName("PIDatabaseSecurity")]
class xPIDatabaseSecurity : OMI_BaseResource
{
    [Write] String Security;
    [Key] String Name;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("PI Data Archive name for connection")] String PIDataArchive;
};

